### ISSUE TITLE
Update Readme to explain package.json functionality

### ISSUE THREAD

**Issue by gaggle** [mafintosh/hms#43]
As far as I can tell `package.json` is parsed for entries such as
```
  "private": true,
  "service": {
    "registry": "public/name",
    "ping": true
  }
```
And possibly others I don't know about. It'd be great to have the hms-relevant functionalities explained in the readme file.

**Comment by sorribas** [comment]
This is not an hms issue. This is a start-service issue. Closing.

**Comment by gaggle** [comment]
Moved to https://github.com/e-conomic/start-service/issues/6
