### ISSUE TITLE
Containerized?

### ISSUE THREAD

**Issue by ericelliott** [mafintosh/hms#49]
The use of the word "dock" seems to imply that it's containerized, but it doesn't look like you're trying to use containers or docker.

Maybe mention the relationship / non-relationship to docker containers in the README?

**Comment by gausby** [comment]
The word dock refers to shipping. You are free to do a pull request if you like.

**Comment by ericelliott** [comment]
Yeah, that's the impression that I got. I don't care enough to do a PR. Just thought you might like the feedback. =)

**Comment by gausby** [comment]
There ;)

**Comment by ericelliott** [comment]
:+1:
